# Generated by Django 2.1.2 on 2018-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnewsurl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_filename',
            field=models.CharField(default=None, max_length=350),
        ),
    ]
