# Generated by Django 2.1.2 on 2018-10-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnewsurl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_label',
            field=models.CharField(default='real', max_length=10),
        ),
    ]
