# Generated by Django 2.1.2 on 2018-10-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnewsurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_label',
            name='news_label',
            field=models.CharField(choices=[('f', 'Fake'), ('r', 'Real')], max_length=1),
        ),
        migrations.AlterField(
            model_name='news_stance',
            name='news_stance',
            field=models.CharField(choices=[('Ag', 'Agrees'), ('Da', 'Disagrees'), ('><', 'Discusses'), ('Ur', 'Unrelated')], max_length=2),
        ),
    ]
