# Generated by Django 2.1.2 on 2018-10-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnewsurl', '0002_auto_20181020_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_stance',
            name='news_stance',
            field=models.CharField(choices=[('Ag', 'Agrees'), ('Da', 'Disagrees'), ('D~', 'Discusses'), ('Ur', 'Unrelated')], max_length=2),
        ),
    ]
